modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    # logoFile="gtceu_greenhouse.png"
    authors = "${mod_authors}"
    description = '''${mod_description}'''

    [[dependencies."${mod_id}"]]
        modId = "forge"
        mandatory = true
        versionRange = "[${forge_version},)"
        ordering = "NONE"
        side = "BOTH"

    [[dependencies."${mod_id}"]]
        modId = "minecraft"
        mandatory = true
        versionRange = "[${minecraft_version},)"
        ordering = "NONE"
        side = "BOTH"

    [[dependencies."${mod_id}"]]
        modId = "gtceu"
        mandatory = true
        versionRange = "[${gtceu_version},)"
        ordering = "AFTER"
        side = "BOTH"

    [[dependencies."${mod_id}"]]
        modId = "kubejs"
        mandatory = false
        versionRange = "[${kubejs_version},)"
        ordering = "AFTER"
        side = "BOTH"

